services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/cle:/app/src/cle
    env_file:
      - .env
    command: uvicorn cle.main:app --host 0.0.0.0 --port 8000 --reload
